### ISSUE TITLE
Tabindex on buttons in widget

### ISSUE THREAD

**Issue by lisavandeput** [bsgriggs/pagination#1]
Dear bsgriggs,

I love your widget and use it in my project. But we also need the app to work keyboard only. And when I 'tab' trough the app, the advanced pagination is blocking the tab. We also want the pagination to have a tabindex to trigger the pagination with keyboard only. Is it possible to add a tabindex to the buttons in the widget?

Thanks so much in advance!
Lisa

**Comment by bsgriggs** [comment]
Hi Liza,

Do you need the tab index to be all set to the same value (like -1) or do you need the tab index to be incremented?

**Comment by lisavandeput** [comment]
Hi Benjamin,

The same index is fine. If the tab on the keyboard is working to go trough all the page buttons I will be very happy :)

**Comment by bsgriggs** [comment]
Hi Liza,

[Here](https://github.com/bsgriggs/mendix-advanced-pagination/releases/download/v1.3.0/mendix.AdvancedPagination.mpk) is a pre-release with tab controls. Please give it a test and let me know if it meets your requirement.

**Comment by lisavandeput** [comment]
Hi Benjamin,

Nice it works! But it only works when selecting tabindex = 1 in the systeem
tab. This means that the pagination is the first element for tab in the
page. Since all mendix widgets have tabindex = 0 default. We need to set
every tabindex to 1 in order to work correctly. Is it possible to set the
tabindex to 0 so it is by default in the rigt order?

Thanks so much for your help :)
Lisa

Op wo 5 jul. 2023 17:35 schreef Benjamin Griggs ***@***.***>:

**Comment by bsgriggs** [comment]
Hi Liza,

I'll take a look. In my latest version for render mode 'button', I was still able to tab through the controls even if tabindex was 0. I added a change this morning to render mode 'link' to get the same behavior. 

Did you download the package just now? If not, can you please download a fresh copy? 

If that still doesn't work, can you please include screenshots of your widget's settings, so I can be sure to replicate?

**Comment by lisavandeput** [comment]
Hi Benjamin,

Yes it works! So happy! Thank you so much :)

Op vr 7 jul 2023 om 17:08 schreef Benjamin Griggs ***@***.***
