### ISSUE TITLE
Per-page pagination customisation

### ISSUE THREAD

**Issue by Slovjaninsky** [bsgriggs/pagination#2]
Hello. I'm using the pagination widget and encountered some issues in per-page pagination format.
1. Buttons are named "First page" and "Last page" instead of "Next page" and "Previous page"
2. Next page, previous page and page break icons customisation doesn't work for per-page pagination (for Navigation format of pagination everything works properly).

Please, see the screenshots.
Widget version 2.0.0
![image001](https://github.com/bsgriggs/mendix-advanced-pagination/assets/28998212/0fd1dfd7-efd0-4733-994f-a8d3f1198fad)
![pagination custom](https://github.com/bsgriggs/mendix-advanced-pagination/assets/28998212/eb2c8e0b-3d59-4eca-8e30-cdc93c93d894)
![image002](https://github.com/bsgriggs/mendix-advanced-pagination/assets/28998212/79e1ea21-738b-4dbc-b724-f5a7a8213628)

Thank you for considering changes.

**Comment by bsgriggs** [comment]
Hello,

Nice catch! I've fixed the icon customization in [release 2.0.1 ](https://github.com/bsgriggs/mendix-advanced-pagination/releases/tag/v2.0.1). 

I'm not sure I understand your first point. The order of the button labels appears to be correct: Previous, First, Last, Next. Am I missing something?
<img width="1198" alt="Screenshot 2023-12-22 at 12 45 36 PM" src="https://github.com/bsgriggs/mendix-advanced-pagination/assets/47681665/b628196b-c1e2-4746-91bf-b4b7e00a06f9">

**Comment by Slovjaninsky** [comment]
> Hello,
> 
> Nice catch! I've fixed the icon customization in [release 2.0.1 ](https://github.com/bsgriggs/mendix-advanced-pagination/releases/tag/v2.0.1).
> 
> I'm not sure I understand your first point. The order of the button labels appears to be correct: Previous, First, Last, Next. Am I missing something? <img alt="Screenshot 2023-12-22 at 12 45 36 PM" width="1198" src="https://private-user-images.githubusercontent.com/47681665/292561028-b628196b-c1e2-4746-91bf-b4b7e00a06f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjg0MTEsIm5iZiI6MTcwMzI2ODExMSwicGF0aCI6Ii80NzY4MTY2NS8yOTI1NjEwMjgtYjYyODE5NmItYzFlMi00NzQ2LTkxYmYtYjRiN2UwMGEwNmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE4MDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYWNiMTE0ZTI4ODZlNGE5Y2M4Yzg1MzI4ZWVjYTY3ZmFhNmEwNzg5YmUzNjQ5NTg1YjhkZWQ5ZTUxYmRlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sVrHJQFRVOqtnc0aabBpnfnYeg0gHLi59kze-jg64Ys">

Hey, thanks for the quick fix. I will give it a test as soon as possible :D
Regarding the naming, I was referencing the "Buttons" tab, where (as far as I understand that correctly) you should be able to customise the icons of "Previous" and "Next", but it's written "First" and "Last" (which is a bit pointless since we have First and Last it as numbers).

And thanks for maintaining this widget, find it really useful in my project. 

Wish you Marry Christmas!
Slovjaninsky

**Comment by bsgriggs** [comment]
Ahh makes sense. Thanks for using my widget 😃 

Merry Christmas!
