### ISSUE TITLE
Hi, How to do the search selection (eg Search department)

### ISSUE THREAD

**Issue by BrightKnight0110** [bsgriggs/pagination#3]
![image](https://github.com/bsgriggs/mendix-advanced-pagination/assets/81424151/369d7462-b296-4083-b835-ed68c962af3c)
Can you show the microflow for this ? Thanks a lot if you can help

**Comment by bsgriggs** [comment]
Hi, 
Please see this section of the read-me: https://github.com/bsgriggs/mendix-advanced-pagination?tab=readme-ov-file#create-the-pagination-module 
You need the **ACT_Pagination_Search** microflow to set the page back to page 1 and trigger a refresh
